main: name.richardson.james.reservation.Reservation
database: true
version: 1.0.1
name: Reservation
description: Manage player slots on your server.
website: https://github.com/grandwazir/Reservation
author: James Richardson (grandwazir)
commands:
  reserve:
    description: The root reservations command
    usage: /reserve <add|remove|list>