main: name.richardson.james.bukkit.reservation.Reservation
version: ${project.version}
name: ${project.name}
description: Manage player slots on your server.
website: https://github.com/grandwazir/Reservation
author: James Richardson (grandwazir)
commands:
  reserve:
    description: The root reservations command
    usage: /reserve <add|remove|list>
